version: '3'
 
services:

  app_prod:
    build: 
      context: .
      dockerfile: Dockerfile.prod
    depends_on:
      - db_prod
    restart: always
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/home/app

  db_prod:
    image: postgres:14.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      # Si no declaro nombre por defecto es "postgres"
      POSTGRES_USER: ${DB_USERNAME}
    container_name: gastos_db_prod
    volumes: 
      - psql_prod:/var/lib/postgresql/data

volumes:
  psql_prod: