import { ApiProperty } from '@nestjs/swagger';
import { IsString } from 'class-validator';

export class LoginGoogleDto {
  @ApiProperty({
    description: 'Token generated by Google Sign In',
    example: '143a3eea-edc9-409d-b448-750ce50b9bf0',
  })
  @IsString()
  tokenGoogle: string;
}
